apiVersion: v1
# In Kubernetes, a Service is a method for exposing a network application that
# is running as one or more Pods in your cluster. Exposes a set of Pods in a
# Deployment by providing Load Balancing and Network access
kind: Service
metadata:
  name: my-service
spec:
  # The set of Pods targeted by a Service is usually determined by a selector
  # that you define. Selector label key-value pairs must match
  # Deployment.spec.template.metadata.labels key-value pairs
  selector:
    app: nginx
  # type can be
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
# metadata about the Deployment object
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    version: 0.0.1
# what we want the Deployment's desired state
# to be
spec:
  replicas: 3
  # tells k8s which pods the Deployment manages
  selector:
    # must match spec.template.metadata.labels
    matchLabels:
      app: nginx
  # The "template" here defines the Pod spec
  # for each replica:
  template:
    metadata:
      labels:
        app: nginx
    # This section describes what the Pod should
    # run—like the container image, exposed ports,
    # and other configurations.
    spec:

      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/config
            name: config-volume

        #TODO probes
#        startupProbe:
#        livenessProbe:
#        readinessProbe:

      # volumes declared available to the
      # pod(s)
      volumes:
        # spec.template.spec.volumes[].name
        # must match spec.template.spec.containers[].volumeMounts[].name
        - name: config-volume
          configMap:
            name: config


---
apiVersion: v1
kind: ConfigMap
data:
  config.yaml: |
    some: "config"
    more: config
    enabled: true
    moreconfig: 5
metadata:
  name: config